const PostsActionTypes = {
  FETCH_POSTS_START: "FETCH_POSTS_START",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  TOGGLE_ADD_POST_SHOW: "TOGGLE_ADD_POST_SHOW",
  ADD_POST: "ADD_POST",
  SUBMIT_POST_START: "SUBMIT_POST_START",
  SUBMIT_POST_SUCCESS: "SUBMIT_POST_SUCCESS",
  SUBMIT_POST_FAILURE: "SUBMIT_POST_ERROR",
  CLEAR_ADD_POST: "CLEAR_ADD_POST",
};

export default PostsActionTypes;
